// LONG MATTR category registry — the site's 6 REAL content categories
// (general daily wrap + the 5 agent categories). `slug` is the /:category
// route; `feed` tells CategoryNewsPage what to load; `account` maps to the
// newsletter_categories row used for signed-in subscriptions.
export const LM_CATEGORIES = [
  {
    slug: 'general',
    tile: '/figma/menu/international.png',
    title: 'The Daily',
    hero: 'The Daily',
    desc: "The day's biggest stories across India, world, business, sports and tech — in ten sharp reads.",
    bg: '#FFF2EB',
    image: '/figma/category-international.png',
    imageBase: '/figma/category-international-base.png',
    feed: { general: true },
    account: { slug: 'national', type: 'news_rhythm' },
  },
  {
    slug: 'money-matters',
    tile: '/figma/menu/money-matters.png',
    title: 'Money & Stock Markets',
    hero: 'Money & Markets',
    desc: 'Get market updates, business trends, investing insights, IPOs, personal finance.',
    bg: '#F5F0FF',
    image: '/figma/category-money-markets.png',
    feed: { category: 'Money Matters', topics: ['Business'] },
    account: { slug: 'money-matters', type: 'category_small_articles' },
  },
  {
    slug: 'case-studies',
    tile: '/figma/menu/case-studies.png',
    title: 'Corporate Cases',
    hero: 'Corporate Cases',
    desc: 'One sharp business case study every day — strategy, market moves, and what they mean.',
    bg: '#F4F4F6',
    image: '/figma/category-entertainment.gif',
    poster: '/figma/category-entertainment-still.png',
    feed: { caseStudies: true },
    account: { slug: 'corporate-case', type: 'case_study_daily' },
  },
  {
    slug: 'wellness-daily',
    tile: '/figma/menu/wellness-daily.png',
    title: 'Wellness Daily',
    hero: 'Wellness Daily',
    desc: 'Evidence-led health, fitness, sleep, and mental-wellness stories for working professionals.',
    bg: '#E9F4EB',
    image: '/figma/category-wellness.png',
    feed: { category: 'Wellness Daily' },
    account: { slug: 'wellness-daily', type: 'category_small_articles' },
  },
  {
    slug: 'policy-partner',
    tile: '/figma/menu/policy-partner.png',
    title: 'Politics & Power',
    hero: 'Politics & Power',
    desc: 'Policy in plain English — courts, regulators, and the decisions that touch your life.',
    bg: '#ECE6F0',
    image: '/figma/category-national-politics.png',
    feed: { category: 'Policy Partner' },
    account: { slug: 'policy-partner', type: 'category_small_articles' },
  },
  {
    slug: 'real-estate',
    tile: '/figma/menu/real-estate.png',
    title: 'Real Estate',
    hero: 'Real Estate',
    desc: 'Launches, handovers, infrastructure, and regulation across India’s big property markets.',
    bg: '#EBF4FF',
    image: '/figma/category-real-estate.png',
    feed: { category: 'Real Estate' },
    account: { slug: 'real-estate', type: 'category_small_articles' },
  },
]

export const lmCategoryBySlug = (slug) => LM_CATEGORIES.find((c) => c.slug === slug) || null
